function []=fiber_read(path)

%==========================================================================
%  Subroutine to read fiber data
%==========================================================================
%
% Reads *.csv with coordinates, sorts them in upropriate way
%
% INput:        *.csv (Generated in OsiriX)
%               *.dcm of reference FGRE set
%               both should be in the same folder
%
% OUTput:       *.mat file in root folder
%               images of fibers overlayed over FGRE reference set
%
%--------------------------------------------------------------------------
% written by Vadim Malis
% 12/14 at UCSD RIL
%==========================================================================


cd(path)

%number of fibers identified (Robert did 7 fibers per slice)
number_of_fibers=7;

%initial structure;
fiber.id=nan;
fiber.slice_location=nan;    
fiber.x=zeros(number_of_fibers,2);
fiber.y=zeros(number_of_fibers,2);

path=pwd;

%valid for MAC
[subject_list,N]=folder_list(path);


multiWaitbar('Getting fiber data per subject...', 0,'Color', 'r');

for i=1:N
    
cd(subject_list(i).name)

    %valid for MAC
    [study_list,M]=folder_list(pwd);
    
    multiWaitbar('per study...', 0,'Color', 'g');
    for j=1:M
    cd(study_list(j).name)
    cd('patient')
    csv_filename=dir('*.csv');
    % csv file is generated by Robert and is described in HOWTO_2dSR.pdf
    % you can comment 8 lines below if you have different file
    
    
    %Robert and I were placing fiber coordinates in OsiriX using different
    %tools. Point tool gives each point seperatley, while line combines
    %verticies in one object so aproach to read is different.
    %Line tool files are usually less than 13kb while point tool are > 12
    %
    % Future release will have second option (point tool from OsiriX) only
    %
    
    dicomfile=dir('*.dcm');
    I=dicomread(dicomfile(5).name);
    figure
    imshow(mat2gray(I))
    choice = questdlg('Is th orientation left or right sided?', ...
	'Orientation', ...
	'Left','Right','Right');
     % Handle response
        switch choice
            case 'Left'
                const=512;
                mult=-1;
            case 'Right'
                const=0;
                mult=1;
        end
    close
    
    if csv_filename.bytes<12500
    
    fileID = fopen(csv_filename(1).name);
    Header = textscan(fileID,'%s',21,'Delimiter',',');
    Data   = textscan(fileID,'%d %d %d %d %d %d %s %s %f %f %f %d %d %d %d %f %f %f %f %f %f %f %f %f %f','Delimiter',',');
    fclose(fileID);  
    in=Data{1,1};
    X_DATA_temp=[Data{1,19} Data{1,24}];
    Y_DATA_temp=[Data{1,20} Data{1,25}];

    X_DATA=reshape(X_DATA_temp.',[],1);
    Y_DATA=reshape(Y_DATA_temp.',[],1);
    
    else   
    
    fileID = fopen(csv_filename(1).name);
    Header = textscan(fileID,'%s',21,'Delimiter',',');
    Data   = textscan(fileID,'%d %d %d %d %d %d %s %s %f %f %f %d %d %d %d %f %f %f %f %f','Delimiter',',');
    fclose(fileID);  
    in=Data{1,1};
    X_DATA=Data{1,19};
    Y_DATA=Data{1,20};
    
    end
   
    slice_n=unique(in);

    
    dicom_list=dir('*dcm');  
    n_dcm=length(dicom_list);   %number of dicom images in reference FGRE
     
    m=1;                        %initial study(series) number
    l=1;                        %initial fiber number
    k=slice_n+1;    % Notation in csv file is a bit sloppy slices 
                        % are numerated from the
                        % end (comapring with dicom header)            
    
     multiWaitbar('per slice...', 0,'Color', 'b');                   

     
     Y=zeros(number_of_fibers,2);
     X=zeros(number_of_fibers,2);
  
     
    for q=1:size(k,1)        
    info=dicominfo(dicom_list(k(q)).name);    
    I=dicomread(dicom_list(k(q)).name); 
    temp(m).id=info.PatientID;
    temp(m).slice_location=info.SliceLocation;    

    
    x=mult*X_DATA(l:l+number_of_fibers*2-1)+const;
    y=Y_DATA(l:l+number_of_fibers*2-1);
    l=l+number_of_fibers*2;


    
    % fiber coordinates sometimes were not picked up one by one 
    % in consecutive order automatic sorting is performed
    % 
    % the following assumption is made:
    % end point is at least 3 pixels to the right from the x coordinate of
    % fiber initial x coordinate
    
%-------------------------------sort engine--------------------------------
for ii=1:number_of_fibers

            [Y(ii,1),index]=max(y);       
            X(ii,1)=x(index);
            y(index)=[];
            x(index)=[];
            
            index=fiber_end(X(ii,1),Y(ii,1),x,y);
        
            Y(ii,2)=y(index);
            X(ii,2)=x(index);
            
            y(index)=[];
            x(index)=[];
            
end
%--------------------------------------------------------------------------
    
    %save image
    h=figure;
    set(gcf,'Visible','off');
    
    if const==512
    imshow(mat2gray(flip(I,2)),'Border','tight') ;
    else
    imshow(mat2gray(I),'Border','tight') ;    
    end
    
    hold on  
    for o=1:number_of_fibers  
    plot(X(o,:),Y(o,:),'r-')
    filename=sprintf('slice-%d.png',k(q));
    set(gcf, 'PaperPositionMode', 'manual');
    set(gcf, 'PaperUnits', 'inches');
    set(gcf, 'PaperPosition', [1 1 2 2]);
    print(h,'-dpng',filename);
    end
    hold off
    clear h
    
    % writing sorted x,y data to the structure
    temp(m).x=X;
    temp(m).y=Y;
    
    m=m+1;
    multiWaitbar('per slice...', q/size(k,1)); 
    end
    multiWaitbar('per slice...', 'Close'); 
    
    
    fiber=[fiber, temp];
    clear temp  
    cd ..
    cd ..
    multiWaitbar('per study...', j/M);
    end
    multiWaitbar('per study...', 'Close'); 
    
    cd ..
multiWaitbar('Getting fiber data per subject...', i/N);
end

multiWaitbar('Getting fiber data per subject...', 'Close'); 

fiber(1)=[];
save ('fiber data.mat','fiber')

clear all
clc
end